name: Generate Sitemap
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://yourdomain.com
        path-to-root: .
        include-pdf: false
        include-html: true
        sitemap-format: xml
        drop-html-extension: true
        exclude-paths: |
          template.html
          posts/assets/*
    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    
    - name: Check for sitemap changes
      id: verify-changed-files
      run: |
        echo "Checking if sitemap.xml exists and has changes..."
        ls -la sitemap.xml || echo "sitemap.xml not found"
        
        if [ ! -f "sitemap.xml" ]; then
          echo "Sitemap file not found, treating as new file"
          echo "changed=true" >> $GITHUB_OUTPUT
        elif git diff --quiet HEAD -- sitemap.xml 2>/dev/null; then
          echo "No changes detected in sitemap.xml"
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected in sitemap.xml"
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
        echo "Git status:"
        git status --porcelain
    
    - name: Commit sitemap changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml
        git commit -m "Update sitemap.xml - ${{ steps.sitemap.outputs.url-count }} URLs found"
        git push
